In [10]:
from keras.models import load_model
from PIL import Image, ImageOps
import numpy as np

# Load the model
model = load_model('keras_model.h5', compile=False)

# Create the array of the right shape to feed into the keras model
# The 'length' or number of images you can put into the array is
# determined by the first position in the shape tuple, in this case 1.
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
# Replace this with the path to your image
image = Image.open('/content/drive/MyDrive/Datasets/dry/dry(102).jpg')
#resize the image to a 224x224 with the same strategy as in TM2:
#resizing the image to be at least 224x224 and then cropping from the center
size = (224, 224)
image = ImageOps.fit(image, size, Image.ANTIALIAS)

#turn the image into a numpy array
image_array = np.asarray(image)
# Normalize the image
normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
# Load the image into the array
data[0] = normalized_image_array

# run the inference
prediction = model.predict(data)
print(data.shape)
print(data)
print(index(prediction))


(1, 224, 224, 3)
[[[[-0.8346457  -0.9055118  -0.88188976]
   [-0.8346457  -0.9055118  -0.88188976]
   [-0.8425197  -0.9212598  -0.8976378 ]
   ...
   [-0.8267716  -0.8976378  -0.87401575]
   [-0.8346457  -0.88188976 -0.86614174]
   [-0.8188976  -0.88188976 -0.8582677 ]]

  [[-0.8503937  -0.92913383 -0.9055118 ]
   [-0.8503937  -0.92913383 -0.9055118 ]
   [-0.8582677  -0.92913383 -0.9055118 ]
   ...
   [-0.8267716  -0.8976378  -0.87401575]
   [-0.8503937  -0.9133858  -0.8897638 ]
   [-0.8267716  -0.8976378  -0.87401575]]

  [[-0.8267716  -0.9133858  -0.88188976]
   [-0.8110236  -0.8976378  -0.86614174]
   [-0.8267716  -0.8976378  -0.87401575]
   ...
   [-0.8110236  -0.88188976 -0.8582677 ]
   [-0.8425197  -0.9133858  -0.8897638 ]
   [-0.8503937  -0.9212598  -0.8976378 ]]

  ...

  [[-0.79527557 -0.88188976 -0.8503937 ]
   [-0.8110236  -0.8976378  -0.86614174]
   [-0.79527557 -0.88188976 -0.8346457 ]
   ...
   [-0.8188976  -0.9055118  -0.8582677 ]
   [-0.8110236  -0.8976378  -0.86614174]